pipeline:
  publish:
    image: plugins/docker
    repo: registry.evilcorp.gq/matteojoliveau/lodbot
    registry: registry.evilcorp.gq
    tags: latest
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://kubernetes.company.org
    namespace: bots
    deployment: lodbot
    repo: registry.evilcorp.gq/matteojoliveau/lodbot
    container: lodbot
    tag: latest
    secrets: [kubernetes_token]