pipeline:
  build:
    image: plugins/docker
    repo: registry.evilcorp.gq/matteojoliveau/lodbot
    registry: registry.evilcorp.gq
    tags: "${DRONE_COMMIT_SHA:0:8}"
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://evilcorp.gq:8443/k8s/clusters/c-tvqpd
    kubernetes_token: "${KUBERNETES_TOKEN}"
    namespace: bots
    deployment: lodbot
    repo: registry.evilcorp.gq/matteojoliveau/lodbot
    container: lodbot
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [kubernetes_token]