pipeline:
  build:
    image: plugins/docker
    repo: registry.evilcorp.gq/matteojoliveau/lodbot
    registry: registry.evilcorp.gq
    tags: "${DRONE_COMMIT_SHA:0:8}"

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://evilcorp.gq:8443/k8s/clusters/c-tvqpd
    namespace: bots
    deployment: loadbot
    repo: registry.evilcorp.gq/matteojoliveau/lodbot
    container: lodbot
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [kubernetes_token]
    
    # image: peloton/drone-k8s-deployment
    # url: https://evilcorp.gq:8443/k8s/clusters/c-tvqpd
    # insecure: true
    # deployment_names: lodbot
    # container_names: lodbot
    # namespaces: bots
    # docker_image: "registry.evilcorp.gq/matteojoliveau/lodbot:${DRONE_COMMIT_SHA:0:8}"