stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: matteojoliveau/lodbot:latest
      pushRemote: true
      registry: registry.evilcorp.gq
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
timeout: 60
