stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: matteojoliveau/lodbot:latest
      pushRemote: true
      registry: registry.evilcorp.gq
    when:
      branch:
        include:
        - master
      event:
        include:
        - push
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
timeout: 60
