apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:bots:lodbot"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: 2018-08-10T13:15:08Z
  name: lodbot
  namespace: bots
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: lodbot
    uid: 675be27e-9c9f-11e8-bd9d-0050563d3c84
  resourceVersion: "487570"
  selfLink: /api/v1/namespaces/bots/services/lodbot
  uid: 675d742e-9c9f-11e8-bd9d-0050563d3c84
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-bots-lodbot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
 
 ---
 apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/creatorId: user-qcdlv
  creationTimestamp: 2018-08-10T13:15:08Z
  generation: 5
  labels:
    workload.user.cattle.io/workloadselector: deployment-bots-lodbot
  name: lodbot
  namespace: bots
  resourceVersion: "20631614"
  selfLink: /apis/apps/v1beta2/namespaces/bots/deployments/lodbot
  uid: 675be27e-9c9f-11e8-bd9d-0050563d3c84
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-bots-lodbot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-bots-lodbot
    spec:
      affinity: {}
      containers:
      - env:
        - name: BOT_TOKEN
          value: 390584979:AAHArotLAfKL5eEl6HuA2nzwycikWvtTgvk
        image: registry.evilcorp.gq/matteojoliveau/lodbot:latest
        imagePullPolicy: Always
        name: lodbot
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: evilcorp
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-08-10T18:53:23Z
    lastUpdateTime: 2018-08-10T19:00:13Z
    message: ReplicaSet "lodbot-5fcc57b546" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-11-08T10:31:54Z
    lastUpdateTime: 2018-11-08T10:31:54Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

